'use strict'
const { chromium } = require('playwright')
;(async () => {
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage({ viewport: { width: 1400, height: 900 } })
  await page.goto('http://localhost:3001', { waitUntil: 'networkidle', timeout: 15000 })
  await page.waitForTimeout(1500)
  await page.screenshot({ path: 'C:/tmp/final-home.png' })
  await page.evaluate(() => navTo('dashboard'))
  await page.waitForTimeout(800)
  await page.screenshot({ path: 'C:/tmp/final-orders.png' })
  await page.evaluate(() => navTo('settings'))
  await page.waitForTimeout(800)
  await page.screenshot({ path: 'C:/tmp/final-settings.png' })
  await page.evaluate(() => switchSettingsTab('keywords', document.querySelectorAll('.settings-tab-btn')[1]))
  await page.waitForTimeout(600)
  await page.screenshot({ path: 'C:/tmp/final-keywords.png' })
  await page.evaluate(() => navTo('copilot'))
  await page.waitForTimeout(800)
  await page.screenshot({ path: 'C:/tmp/final-copilot.png' })
  await browser.close()
  console.log('Done')
})()
